### ISSUE TITLE
SubversionException: ("Can't open file '/var/www/svn/Ipopt/db/revprops/1861': Too many open files", 24)

### ISSUE THREAD

**Issue by svigerske** [coin-or/Ipopt#202]
Issue created by migration from Trac.

Original creator: chenscan

Original creation time: 2013-06-19 07:41:11

Assignee: ipopt-team

Version: 3.11

#### How to Reproduce

While doing a GET operation on `/changeset/2338/releases/3.11.1`, Trac issued an internal error.

_(please provide additional details here)_

Request parameters:
```
{'format': u'zip',
 'new': u'2338',
 'new_path': u'/releases/3.11.1',
 'old_path': u'/'}
```

User agent: `Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1`

#### System Information
系统信息不可用

#### Enabled Plugins
插件信息不可用

#### Python Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/trac/web/main.py", line 525, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.6/site-packages/trac/web/main.py", line 246, in dispatch
    resp = chosen_handler.process_request(req)
  File "/usr/lib/python2.6/site-packages/trac/versioncontrol/web_ui/changeset.py", line 349, in process_request
    self._render_zip(req, filename, repos, data)
  File "/usr/lib/python2.6/site-packages/trac/versioncontrol/web_ui/changeset.py", line 777, in _render_zip
    zipinfo.date_time = new_node.last_modified.utctimetuple()[:6]
  File "/usr/lib/python2.6/site-packages/trac/versioncontrol/api.py", line 1059, in <lambda>
    last_modified = property(lambda self: self.get_last_modified())
  File "/usr/lib/python2.6/site-packages/trac/versioncontrol/svn_fs.py", line 803, in get_last_modified
    core.SVN_PROP_REVISION_DATE, self.pool())
  File "/usr/lib64/python2.6/site-packages/libsvn/fs.py", line 729, in svn_fs_revision_prop
    return apply(_fs.svn_fs_revision_prop, args)
SubversionException: ("Can't open file '/var/www/svn/Ipopt/db/revprops/1861': Too many open files", 24)
```

**Comment by svigerske** [comment]
Comment by @svigerske created at 2013-06-21 08:52:39

Which page/link did you try to open when you got this error?

I also got such an error recently, but could not reproduce it anymore.

**Comment by svigerske** [comment]
Comment by @svigerske created at 2013-07-01 13:01:26

Resolution: worksforme
